fix linting (#85)
This PR fixes:
- updated `golangci/golangci-lint-action` to v6
- Created .golangci.yml with additional build tags which are required to
build
- fixed the following issues
```shell
cmd/ai-services/cmd/application/application.go:30:45: Error return value of `(*github.com/spf13/pflag.FlagSet).MarkHidden` is not checked (errcheck)
        ApplicationCmd.PersistentFlags().MarkHidden("tool-image")
                                                   ^
cmd/ai-services/cmd/application/create.go:222:28: Error return value of `createCmd.MarkFlagRequired` is not checked (errcheck)
        createCmd.MarkFlagRequired("template")
                                  ^
cmd/ai-services/cmd/application/image/image.go:23:37: Error return value of `ImageCmd.MarkPersistentFlagRequired` is not checked (errcheck)
        ImageCmd.MarkPersistentFlagRequired("template")
                                           ^
cmd/ai-services/cmd/application/logs.go:45:26: Error return value of `logsCmd.MarkFlagRequired` is not checked (errcheck)
        logsCmd.MarkFlagRequired("pod")
                                ^
cmd/ai-services/cmd/application/model/download.go:24:30: Error return value of `downloadCmd.MarkFlagRequired` is not checked (errcheck)
        downloadCmd.MarkFlagRequired("template")
                                    ^
cmd/ai-services/cmd/application/model/download.go:26:32: Error return value of `(*github.com/spf13/pflag.FlagSet).MarkHidden` is not checked (errcheck)
        downloadCmd.Flags().MarkHidden("tool-image")
                                      ^
cmd/ai-services/cmd/application/model/list.go:24:26: Error return value of `listCmd.MarkFlagRequired` is not checked (errcheck)
        listCmd.MarkFlagRequired("template")
                                ^
internal/pkg/cli/helpers/helper.go:114:10: Error return value of `f.Close` is not checked (errcheck)
                f.Close()
                       ^
cmd/ai-services/cmd/bootstrap/configure.go:147:121: printf: fmt.Errorf format %w has arg string(out) of wrong type string (govet)
                return fmt.Errorf("❌ failed to create sentient group and add current user to the sentient group. Error: %w, output: %w", err, string(out))
                                                                                                                                      ^
9 issues:
* errcheck: 8
* govet: 1
```

Signed-off-by: Manjunath Kumatagi <mkumatag@in.ibm.com>